from lista_de_pkm import pokemon as pkm
def evolucao(pkm_evo):
	if(pkm_evo[0].lower())=='bulbasaur':
		pokemon_evoluido=pkm[1]
	elif(pkm_evo[0].lower())=='ivysaur':
		pokemon_evoluido=pkm[2]
	elif(pkm_evo[0].lower())=='charmander':
		pokemon_evoluido=pkm[4]
	elif(pkm_evo[0].lower())=='charmeleon':
		pokemon_evoluido=pkm[5]
	elif(pkm_evo[0].lower())=='squirtle':
		pokemon_evoluido=pkm[7]
	elif(pkm_evo[0].lower())=='wartortle':
		pokemon_evoluido=pkm[8]
	elif(pkm_evo[0].lower())=='weedle':
		pokemon_evoluido=pkm[10]
	elif(pkm_evo[0].lower())=='kakuna':
		pokemon_evoluido=pkm[11]
	elif(pkm_evo[0].lower())=='pidgey':
		pokemon_evoluido=pkm[13]
	elif(pkm_evo[0].lower())=='pidgeotto':
		pokemon_evoluido=pkm[14]
	elif(pkm_evo[0].lower())=='poliwag':
		pokemon_evoluido=pkm[16]				
	elif(pkm_evo[0].lower())=='poliwhirl':
		pokemon_evoluido=pkm[17]
	elif(pkm_evo[0].lower())=='pikachu':
		pokemon_evoluido=pkm[19]
	elif(pkm_evo[0].lower())=='voltorb':
		pokemon_evoluido=pkm[21]
	elif(pkm_evo[0].lower())=='jigglypuff':
		pokemon_evoluido=pkm[23]
	elif(pkm_evo[0].lower())=='mankey':
		pokemon_evoluido=pkm[25]
	elif(pkm_evo[0].lower())=='machop':
		pokemon_evoluido=pkm[26]
	elif(pkm_evo[0].lower())=='ponyta':
		pokemon_evoluido=pkm[28]								
	return pokemon_evoluido